---
- hosts: monitoring
  gather_facts: false
  vars: 
    prometheus_version: "2.45.0"
    grafana_version: "10.0.3-1"
  tasks:
    - include_tasks: prometheus.yml
    - include_tasks: grafana.yml
    - systemd:
        daemon_reexec: true
      become: true